### ISSUE TITLE
Do not discard entire substitution upon simplifiable cycle

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1069]
Consider a substitution with a simplifiable cycle, such as

```
x = andBool(x, true) ∧ y = a()
```

Although applying the substitution for `x` would not terminate, we could apply the substitution for `y`. Presently, we convert this entire substitution to a predicate and apply none of it. This blocks further simplification because we cannot apply the rest of the substitution.

See also: #998, #1002, #1052 

---

- [x] Factor a function out of `normalizeSubstitution` which returns the normalized and denormalized parts of the substitution. (#1085)
- [x] Duplicate the predicate simplifier predicate simplifier into the unifier. (#1113)
- [x] Ensure that the unifier predicate simplifier does not call the predicate simplifier predicate simplifier, and vice versa. (#1113)
- [ ] Modify the predicate simplifier predicate simplifier to call the extracted function which returns the normalized and denormalized parts of the substitution, and only promote the denormalized part to the predicate. (#1118)

**Comment by ttuegel** [comment]
This is also related to some proofs sending too many queries to Z3.
