### ISSUE TITLE
Iteration 19

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1716]
## Iteration 19

01 April 2020 to 15 April 2020

[Iteration 19 Milestone](https://github.com/kframework/kore/milestone/17)

### Threads

- Bugs
  - [ ] #1648: No branching in K-EQUAL hooks
  - [x] #1639: Better Map unification needed
  - [x] #1679: List of cells with symbolic tail not supported
  - [ ] #1669: Reasoning about definedness of Map-type collection cells
  - [x] #1560 #1473 #1602: Equation application
  - [ ] #1665: Beacon chain: process-slots-base1-spec
  - [ ] #1702: Z3 error in symbolic testing full test-approve
- Usability
  - [x] #1695: Underscore not supported in module name
  - [ ] Better `--help`, especially for debugging options
- Features
  - [ ] #1628: kore-repl: stepf should advance to the branching point
  - [ ] #1442: Predicate should have a distinguished representation
- Investigate
  - [ ] #1349: Comparatively bad performance on some concrete tests
  - [ ] #1350: KEVM concrete tests with unusually high kernel time
  - [ ] #1348: KEVM concrete tests time out
  - [ ] #704: Bag cell collections
