### ISSUE TITLE
Iteration 20

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1750]
## Iteration 20

15 April 2020 to 29 April 2020

[Iteration 20 Milestone](https://github.com/kframework/kore/milestone/18)

### Process

We have enough users now that I think we should document user-facing changes in a changelog. I have started to keep a changelog following the format of [keepachangelog.com](https://keepachangelog.com/en/1.0.0/).

I will start to create "releases" at the end of each iteration. This will only consist of increasing the version number and adding a tag in Git. We will continue to run all tests on every pull request and merge into master; there will be no release branches, feature freezes, backports, etc. We only want to give users a little nudge when they are using an older version. I think this will also make it easier to triage bug reports; compare

```
A: "I have this problem using version ⟨commit hash⟩."
B: "Hold on, I have to look at `git log` because we might have fixed that...
```

versus:

```
A: "I have this problem using version 0.21.0"
B: "The current version is 0.25.0, so that version is 2 months behind."
B: "Please try again with a newer Kore."
```

### Threads

- Bugs
  - [x] #1648: No branching in K-EQUAL hooks
  - [ ] #1665: Beacon chain: process-slots-base1-spec
    This issue has been carried over through two iterations (since Iteration 18) so we are going to reduce the scope of the solution significantly.
  - [x] #1702: Z3 error in symbolic testing full test-approve
- Usability
  - [x] #1722: Add a help entry on the command-line for each type of log entry
  - [x] #1726: Rename the "substitution coverage" error
  - [ ] #1731: Forbid injections into hooked sorts
- Features
  - [ ] #1628: kore-repl: stepf should advance to the branching point
  - [ ] #1749: Hot-spot: targetRuleVariables
  - [ ] #1545: Respect the identity of variables
- Investigate
  - [ ] #1349: Comparatively bad performance on some concrete tests
  - [ ] #1350: KEVM concrete tests with unusually high kernel time
  - [ ] #1348: KEVM concrete tests time out
