### ISSUE TITLE
Iteration 21

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1770]
## Iteration 21

29 April 2020 to 13 May 2020

[Iteration 21 Milestone](https://github.com/kframework/kore/milestone/19)

### Threads

- Features
  - [x] #1628: kore-repl: stepf should advance to the branching point
  - [x] #1749: Hot-spot: targetRuleVariables
  - [ ] #1545: Respect the identity of variables
  - [ ] #1146 #1245 #1630: Function rules with \or patterns
- Bugs
  - [ ] #1648: No branching in K-EQUAL hooks
  - [ ] #1665: Beacon chain: process-slots-base1-spec
  - [ ] #1733: Remove Kore.Internal.SideCondition.andCondition
- Usability
  - [x] #1722: Add a help entry on the command-line for each type of log entry
  - [x] #1726: Rename the "substitution coverage" error
  - [x] #1731: Forbid injections into hooked sorts
- Clean-up
  - [ ] #1767: Remove UnificationError
  - [x] #1739: Package kore-repl alias scripts
- Investigate
  - [ ] #1721: Unevaluated function of List and Map
