### ISSUE TITLE
Iteration 22

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1812]
## Iteration 22

13 May 2020 to 27 May 2020

[Iteration 22 Milestone](https://github.com/kframework/kore/milestone/20)

### Threads

- Features
  - [ ] #1545: Respect the identity of variables
  - [ ] #1146 #1245 #1630: Function rules with \or patterns
  - [x] #1721: Overloading variables
  - [ ] #1827: kore-repl: Use KORE_REPL_OPTS environment variable
- Bugs
  - [x] #1648: No branching in K-EQUAL hooks
  - [ ] #1665: Beacon chain: process-slots-base1-spec
  - [x] #1733: Remove Kore.Internal.SideCondition.andCondition
- Clean-up
  - [ ] ~#1767: Remove UnificationError~
- Investigate
  - [ ] Decision tree for unifying rules
