### ISSUE TITLE
Iteration 23

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1850]
## Iteration 22

27 May 2020 to 10 June 2020

[Iteration 23 Milestone](https://github.com/kframework/kore/milestone/21)

### Threads

- Interactivity
  - [ ] #1827: `KORE_REPL_OPTS`
  - [ ] #1832: Document equation debugging flags
  - [ ] #1843: Logging options in kore-repl
  - [ ] #1824: Printing in kore-repl scripts
- Performance
  - [ ] #1815: Do not rename SideCondition when applying equations
  - [ ] #1442: Predicate should have a distinguished representation
  - [ ] #1348: KEVM tests time-out
  - [ ] #1349: Slow KEVM tests
