### ISSUE TITLE
Iteration 24

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1877]
## Iteration 24

10 June 2020 to 24 June 2020

[Iteration 24 Milestone](https://github.com/kframework/kore/milestone/22)

### Threads

- Bugs
  - [ ] #1767 #1412 #1665: `removeDestination` gets stuck when configuration would be `\bottom`
  - [ ] #1872: Exit code is ignored when final state has side conditions
  - [x] #1843: Logging options in kore-repl
- Performance
  - [x] #1875 #1348 #1349: Do not keep execution graph in memory during execution
  - [x] #1815: Do not rename SideCondition when applying equations
  - [ ] #1442: Predicate should have a distinguished representation
- Interactivity
  - [x] #1827: `KORE_REPL_OPTS`
  - [x] #1832: Document equation debugging flags
