### ISSUE TITLE
Iteration 25

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1912]
## Iteration 25

24 June 2020 to 8 July 2020

[Iteration 25 Milestone](https://github.com/kframework/kore/milestone/23)

### Threads

- Performance
  - [ ] #1897: Generate stack profiles for Kore
  - [ ] #1896: Profile \ceil simplifier in eventlog
  - [ ] #1911: Infer definedness of sub-terms
- Bugs
  - [x] #1900: Bug report contains corrupt error log
  - [x] #1901: Fix the assertConstructorLikeKeys message
  - [x] #1903: Breadth limit does not work
  - [x] #1905: Missing hook: INT.ediv
- User experience
  - [ ] #1906: Validate predicate simplification rules
