### ISSUE TITLE
Iteration 26

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1961]
## Iteration 26

8 July 2020 to 22 July 2020

[Iteration 26 Milestone](https://github.com/kframework/kore/milestone/24)

### Review

I will present my progress on performance profiling.

### Process

For this iteration, I would like to try an experiment: after approving a pull request, the reviewer will also refactor one thing in the pull request. My hopes for this are two-fold: first, that we will get some of the benefits of pair programming despite the distance, and second, that we will get more practice keeping clean code.

### Threads

- Performance
  - [x] #1896: Profile \ceil simplifier in eventlog
  - [ ] #1911: Infer definedness of sub-terms
- Bugs
  - [x] #1960: kore-repl: redirection doesn't work with alias
  - [ ] #1934: Explain error when Z3 crashes
- User experience
  - [x] #1956: kore-repl: debug-equation dynamically
  - [ ] #1957: kore-repl: Abbreviate help command
  - [x] #1958: Log number of concurrent branches during proof
  - [x] #1943: Distinguish stuck proof states
