### ISSUE TITLE
Iteration 27

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2002]
## Iteration 27

22 July 2020 to 5 August 2020

[Iteration 27 Milestone](https://github.com/kframework/kore/milestone/25)

### Process

We will continue to have each pull request reviewer clean-up or refactor appropriately to the size of the pull request.

### Threads

- Performance
  - [ ] #1911: Infer definedness of sub-terms
  - [ ] #1278: Simplify right-hand side of claims
  - [ ] #1988: Warn about poor performance when productivity is low
- Bugs
  - [ ] #1899: kore-repl: exiting successful proof generates a bug report
- User experience
  - [ ] #1992: kore-repl: Do not terminate process on (sub-process) error
  - [ ] #1978: Evaluating functions with partial arguments
  - [ ] #1957: kore-repl: Abbreviate help command
  - [ ] #1869: Warn when a claim is proven without taking any steps
- Features
  - [ ] #1993: Symbolic SET.difference
  - [ ] #1989: Missing hook: SET.inclusion
