### ISSUE TITLE
Iteration 28

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2039]
## Iteration 28

5 August 2020 to 19 August 2020

[Iteration 28 Milestone](https://github.com/kframework/kore/milestone/26)

### Retro

I think that combining review + refactor has improved the quality of our code reviews and gives cleaner code, so let's stick with that.

I have noticed over the last few months that we encounter regressions during development more frequently than I would like. Our testing practices are solid, so that we are fixing bugs before they are merged, but it's still not a nice way to work. For example, for #1911, I made some changes to unification that introduced a regression: the unification code assumed that when the terms are already equal, the configuration term is returned instead of the rule term. This was a intentional decision we made when we developed the unification code, but there isn't a unit test for it or even a comment in the code documenting it. I discovered the problem through an integration test, but an integration test can't tell me what's wrong the way a unit test can.

To help with this, I would like us to adopt some test-driven development practices. The basic test-driven development workflow is:

1. Write a failing unit test.
2. Implement the code which fixes the failing test (no more and no less).
3. Refactor, if appropriate.
4. Repeat.

The purpose of TDD is often thought to be getting 100% test coverage of every line of code, but that's a side-effect (if it happens at all). The purpose is really: make sure there is a test covering every _decision_ we make while developing the code, to get 100% test coverage _of our intent_. The workflow is strict because we tend to make many decisions automatically and unconsciously, but we want to capture those decisions in the tests.

### Threads

- Performance
  - [x] #1911: Infer definedness of sub-terms
  - [ ] #1278: Simplify right-hand side of claims
  - [x] #2028: Rising memory use while profiling
- Bugs
  - [x] #2036: Disable WarnIfLowProductivity when total run time is short
  - [x] #2037: WarnIfLowProductivity does not suggest a corrective action
  - [x] #2014: Symbolic rules for ==String
  - [x] #2019: Symbolic rules for ==Int
  - [ ] #2020: Symbolic rules for SET.in
  - [x] #1993: Symbolic SET.difference
  - [x] #2021: Every leaf of a proof tree should be "proven" or "stuck"
- User experience
  - [x] #1992: kore-repl: Do not terminate process on (sub-process) error
  - [ ] #1978: Evaluating functions with partial arguments
  - [x] #1869: Warn when a claim is proven without taking any steps
