### ISSUE TITLE
Iteration 30

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2114]
## Iteration 30

02 September 2020 to 16 September 2020

[Iteration 30 Milestone](https://github.com/kframework/kore/milestone/28)

### Plan

#2113 tracks open issues with KEVM. We should have these closed by 30 September, or have a concrete plan for any remaining issues.

- Performance
  - [ ] Infer that the right-hand side of claims is defined (#2110)
- Bugs
  - [ ] Apply transitivity of equality (#2095)
  - [x] `==Int` not simplified (#2109)
- User experience
  - [x] Apply function definitions with unification instead of matching (#1630)
  - [ ] Validate simplification and definition equations (#2100)
- Developer experience
  - [x] Instances of MultiOr, MultiAnd are surprising (#1037)
